### PR TITLE
[CW2-53] Subcom display selection

### PR DESCRIPTION
**Pull request by PenTest-duck**
Previously, the list of directors and descriptions of portfolios were too long and took up a lot of vertical space on the page.

Now, a user selection menu is used to display the portfolio description + directors + subcom members in a more efficient way (inspiration from DevSoc).

Screenshot 2024-10-17 at 1 33 48 am

Mobile responsiveness has been covered with grid breakpoints and a side-scrollable selection bar.

Currently, only director names have been filled out - subcom names, images etc. need to be populated into the data structure (but I think this may be for next year since this year is getting outducted away)?

### CODE REVIEW

**Comment by derekxu04** [comment]
hey chris, nice work! looks much nicer

just some points
- maybe not realistic to get headshots of everyone...
- the scrollbar looks a little bad on some browsers, but maybe not worth trying to fix?
- maybe colours could be aligned with rest of colour palette, but not too bad

dom and I are happy to take it from here unless you had time + wanted to finish it off?

**Comment by Wolfdragon24** [comment]
> * maybe not realistic to get headshots of everyone...
I feel like this would work fine even if we don't get headshots of absolutely everyone, though I think people would be submitting something like that for induction anyway?

Would concur on the other aesthetic comments, though yes, up to you if you'd like to keep working on it, Chris

**Comment by derekxu04** [comment]
I don't know how much people would want their faces on the page, but maybe I'm thinking too deep into this

**Comment by derekxu04** [comment]
new changes
image

**Comment by derekxu04** [comment]
new look
image

**Review by derekxu04 — APPROVED** [review]
LGTM

**Review by Wolfdragon24 — APPROVED** [review]

**Pull request merged**
